"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

x = 2
x1 = 1
n = 0
c = 2

while x < 4000000:
    if (x % 2) == 0:
        n += x
    print str(c) + "th term is: " + str(x) + " and the current sum is: " + str(n) + "\n"
    c += 1
    xn = x + x1
    x1 = x
    x = xn
